export enum BibleBook {
    Genesis = 0,
    Exodus = 1,
    Leviticus = 2,
    Numbers = 3,
    Deuteronomy = 4,
    Joshua = 5,
    Judges = 6,
    Ruth = 7,
    FirstSamuel = 8,
    SecondSamuel = 9,
    FirstKings = 10,
    SecondKings = 11,
    FirstChronicals = 12,
    SecondChronicals = 13,
    Ezra = 14,
    Nehemiah = 15,
    Esther = 16,
    Job = 17,
    Psalms = 18,
    Proverbs = 19,
    Ecclesiastes = 20,
    SongOfSolomon = 21,
    Isaiah = 22,
    Jeremiah = 23,
    Lamentations = 24,
    Ezekiel = 25,
    Daniel = 26,
    Hosea = 27,
    Joel = 28,
    Amos = 29,
    Obadiah = 30,
    Jonah = 31,
    Micah = 32,
    Nahum = 33,
    Habakkuk = 34,
    Zephaniah = 35,
    Haggai = 36,
    Zechariah = 37,
    Malachi = 38,
    Matthew = 39,
    Mark = 40,
    Luke = 41,
    John = 42,
    Acts = 43,
    Romans = 44,
    FirstCorinthians = 45,
    SecondCorinthians = 46,
    Galatians = 47,
    Ephesians = 48,
    Philippians = 49,
    Colossians = 50,
    FirstThessalonians = 51,
    SecondThessalonians = 52,
    FirstTimothy = 53,
    SecondTimothy = 54,
    Titus = 55,
    Philemon = 56,
    Hebrews = 57,
    James = 58,
    FirstPeter = 59,
    SecondPeter = 60,
    FirstJohn = 61,
    SecondJohn = 62,
    ThirdJohn = 63,
    Jude = 64,
    Revelation = 65,
}

export const BibleBookNames : Record<BibleBook, string> = {
    [BibleBook.Genesis]: "Genesis",
    [BibleBook.Exodus]: "Exodus",
    [BibleBook.Leviticus]: "Leviticus",
    [BibleBook.Numbers]: "Numbers",
    [BibleBook.Deuteronomy]: "Deuteronomy",
    [BibleBook.Joshua]: "Joshua",
    [BibleBook.Judges]: "Judges",
    [BibleBook.Ruth]: "Ruth",
    [BibleBook.FirstSamuel]: "1 Samuel",
    [BibleBook.SecondSamuel]: "2 Samuel",
    [BibleBook.FirstKings]: "1 Kings",
    [BibleBook.SecondKings]: "2 Kings",
    [BibleBook.FirstChronicals]: "1 Chronicals",
    [BibleBook.SecondChronicals]: "2 Chronicals",
    [BibleBook.Ezra]: "Ezra",
    [BibleBook.Nehemiah]: "Nehemiah",
    [BibleBook.Esther]: "Esther",
    [BibleBook.Job]: "Job",
    [BibleBook.Psalms]: "Psalms",
    [BibleBook.Proverbs]: "Proverbs",
    [BibleBook.Ecclesiastes]: "Ecclesiastes",
    [BibleBook.SongOfSolomon]: "Song of Solomon",
    [BibleBook.Isaiah]: "Isaiah",
    [BibleBook.Jeremiah]: "Jeremiah",
    [BibleBook.Lamentations]: "Lamentations",
    [BibleBook.Ezekiel]: "Ezekiel",
    [BibleBook.Daniel]: "Daniel",
    [BibleBook.Hosea]: "Hosea",
    [BibleBook.Joel]: "Joel",
    [BibleBook.Amos]: "Amos",
    [BibleBook.Obadiah]: "Obadiah",
    [BibleBook.Jonah]: "Jonah",
    [BibleBook.Micah]: "Micah",
    [BibleBook.Nahum]: "Nahum",
    [BibleBook.Habakkuk]: "Habakkuk",
    [BibleBook.Zephaniah]: "Zephaniah",
    [BibleBook.Haggai]: "Haggai",
    [BibleBook.Zechariah]: "Zechariah",
    [BibleBook.Malachi]: "Malachi",
    [BibleBook.Matthew]: "Matthew",
    [BibleBook.Mark]: "Mark",
    [BibleBook.Luke]: "Luke",
    [BibleBook.John]: "John",
    [BibleBook.Acts]: "Acts",
    [BibleBook.Romans]: "Romans",
    [BibleBook.FirstCorinthians]: "1 Corinthians",
    [BibleBook.SecondCorinthians]: "2 Corinthians",
    [BibleBook.Galatians]: "Galatians",
    [BibleBook.Ephesians]: "Ephesians",
    [BibleBook.Philippians]: "Philippians",
    [BibleBook.Colossians]: "Colossians",
    [BibleBook.FirstThessalonians]: "1 Thessalonians",
    [BibleBook.SecondThessalonians]: "2 Thessalonians",
    [BibleBook.FirstTimothy]: "1 Timothy",
    [BibleBook.SecondTimothy]: "2 Timothy",
    [BibleBook.Titus]: "Titus",
    [BibleBook.Philemon]: "Philemon",
    [BibleBook.Hebrews]: "Hebrews",
    [BibleBook.James]: "James",
    [BibleBook.FirstPeter]: "1 Peter",
    [BibleBook.SecondPeter]: "2 Peter",
    [BibleBook.FirstJohn]: "1 John",
    [BibleBook.SecondJohn]: "2 John",
    [BibleBook.ThirdJohn]: "3 John",
    [BibleBook.Jude]: "Jude",
    [BibleBook.Revelation]: "Revelation"
}

export const OsisBookAbbreviations: Record<BibleBook, string> = {
    [BibleBook.Genesis]: "GEN",
    [BibleBook.Exodus]: "EXO",
    [BibleBook.Leviticus]: "LEV",
    [BibleBook.Numbers]: "NUM",
    [BibleBook.Deuteronomy]: "DEU",
    [BibleBook.Joshua]: "JOS",
    [BibleBook.Judges]: "JDG",
    [BibleBook.Ruth]: "RUT",
    [BibleBook.FirstSamuel]: "1SA",
    [BibleBook.SecondSamuel]: "2SA",
    [BibleBook.FirstKings]: "1KI",
    [BibleBook.SecondKings]: "2KI",
    [BibleBook.FirstChronicals]: "1CH",
    [BibleBook.SecondChronicals]: "2CH",
    [BibleBook.Ezra]: "EZR",
    [BibleBook.Nehemiah]: "NEH",
    [BibleBook.Esther]: "EST",
    [BibleBook.Job]: "JOB",
    [BibleBook.Psalms]: "PSA",
    [BibleBook.Proverbs]: "PRO",
    [BibleBook.Ecclesiastes]: "ECC",
    [BibleBook.SongOfSolomon]: "SNG",
    [BibleBook.Isaiah]: "ISA",
    [BibleBook.Jeremiah]: "JER",
    [BibleBook.Lamentations]: "LAM",
    [BibleBook.Ezekiel]: "EZK",
    [BibleBook.Daniel]: "DAN",
    [BibleBook.Hosea]: "HOS",
    [BibleBook.Joel]: "JOL",
    [BibleBook.Amos]: "AMO",
    [BibleBook.Obadiah]: "OBA",
    [BibleBook.Jonah]: "JON",
    [BibleBook.Micah]: "MIC",
    [BibleBook.Nahum]: "NAM",
    [BibleBook.Habakkuk]: "HAB",
    [BibleBook.Zephaniah]: "ZEP",
    [BibleBook.Haggai]: "HAG",
    [BibleBook.Zechariah]: "ZEC",
    [BibleBook.Malachi]: "MAL",
    [BibleBook.Matthew]: "MAT",
    [BibleBook.Mark]: "MRK",
    [BibleBook.Luke]: "LUK",
    [BibleBook.John]: "JHN",
    [BibleBook.Acts]: "ACT",
    [BibleBook.Romans]: "ROM",
    [BibleBook.FirstCorinthians]: "1CO",
    [BibleBook.SecondCorinthians]: "2CO",
    [BibleBook.Galatians]: "GAL",
    [BibleBook.Ephesians]: "EPH",
    [BibleBook.Philippians]: "PHP",
    [BibleBook.Colossians]: "COL",
    [BibleBook.FirstThessalonians]: "1TH",
    [BibleBook.SecondThessalonians]: "2TH",
    [BibleBook.FirstTimothy]: "1TI",
    [BibleBook.SecondTimothy]: "2TI",
    [BibleBook.Titus]: "TIT",
    [BibleBook.Philemon]: "PHM",
    [BibleBook.Hebrews]: "HEB",
    [BibleBook.James]: "JAS",
    [BibleBook.FirstPeter]: "1PE",
    [BibleBook.SecondPeter]: "2PE",
    [BibleBook.FirstJohn]: "1JN",
    [BibleBook.SecondJohn]: "2JN",
    [BibleBook.ThirdJohn]: "3JN",
    [BibleBook.Jude]: "JUD",
    [BibleBook.Revelation]: "REV"
}
