export enum BibleBook {
    Genesis = "Genesis",
    Exodus = "Exodus",
    Leviticus = "Leviticus",
    Numbers = "Numbers",
    Deuteronomy = "Deuteronomy",
    Joshua = "Joshua",
    Judges = "Judges",
    Ruth = "Ruth",
    FirstSamuel = "1 Samuel",
    SecondSamuel = "2 Samuel",
    FirstKings = "1 Kings",
    SecondKings = "2 Kings",
    FirstChronicals = "1 Chronicals",
    SecondChronicals = "2 Chronicals",
    Ezra = "Ezra",
    Nehemiah = "Nehemiah",
    Job = "Job",
    Psalms = "Psalms",
    Proverbs = "Proverbs",
    Ecclesiastes = "Ecclesiastes",
    SongOfSolomon = "Song of Solomon",
    Isaiah = "Isaiah",
    Jeremiah = "Jeremiah",
    Lamentations = "Lamentations",
    Ezekiel = "Ezekiel",
    Daniel = "Daniel",
    Hosea = "Hosea",
    Joel = "Joel",
    Amos = "Amos",
    Obadiah = "Obadiah",
    Jonah = "Jonah",
    Micah = "Micah",
    Nahum = "Nahum",
    Habakkuk = "Habakkuk",
    Zephaniah = "Zephaniah",
    Haggai = "Haggai",
    Zechariah = "Zechariah",
    Malachi = "Malachi",
    Matthew = "Matthew",
    Mark = "Mark",
    Luke = "Luke",
    John = "John",
    Acts = "Acts",
    Romans = "Romans",
    FirstCorinthians = "1 Corinthians",
    SecondCorinthians = "2 Corinthians",
    Galatians = "Galatians",
    Ephesians = "Ephesians",
    Philippians = "Philippians",
    Colossians = "Colossians",
    FirstThessalonians = "1 Thessalonians",
    SecondThessalonians = "2 Thessalonians",
    FirstTimothy = "1 Timothy",
    SecondTimothy = "2 Timothy",
    Titus = "Titus",
    Philemon = "Philemon",
    Hebrews = "Hebrews",
    James = "James",
    FirstPeter = "1 Peter",
    SecondPeter = "2 Peter",
    FirstJohn = "1 John",
    SecondJohn = "2 John",
    ThirdJohn = "3 John",
    Jude = "Jude",
    Revelation = "Revelation"
}

export const OsisBookAbbreviations: Record<BibleBook, string> = {
    [BibleBook.Genesis]: "GEN",
    [BibleBook.Exodus]: "EXO",
    [BibleBook.Leviticus]: "LEV",
    [BibleBook.Numbers]: "NUM",
    [BibleBook.Deuteronomy]: "DEU",
    [BibleBook.Joshua]: "JOS",
    [BibleBook.Judges]: "JDG",
    [BibleBook.Ruth]: "RUT",
    [BibleBook.FirstSamuel]: "1SA",
    [BibleBook.SecondSamuel]: "2SA",
    [BibleBook.FirstKings]: "1KI",
    [BibleBook.SecondKings]: "2KI",
    [BibleBook.FirstChronicals]: "1CH",
    [BibleBook.SecondChronicals]: "2CH",
    [BibleBook.Ezra]: "EZR",
    [BibleBook.Nehemiah]: "NEH",
    [BibleBook.Job]: "JOB",
    [BibleBook.Psalms]: "PSA",
    [BibleBook.Proverbs]: "PRO",
    [BibleBook.Ecclesiastes]: "ECC",
    [BibleBook.SongOfSolomon]: "SNG",
    [BibleBook.Isaiah]: "ISA",
    [BibleBook.Jeremiah]: "JER",
    [BibleBook.Lamentations]: "LAM",
    [BibleBook.Ezekiel]: "EZK",
    [BibleBook.Daniel]: "DAN",
    [BibleBook.Hosea]: "HOS",
    [BibleBook.Joel]: "JOL",
    [BibleBook.Amos]: "AMO",
    [BibleBook.Obadiah]: "OBA",
    [BibleBook.Jonah]: "JON",
    [BibleBook.Micah]: "MIC",
    [BibleBook.Nahum]: "NAM",
    [BibleBook.Habakkuk]: "HAB",
    [BibleBook.Zephaniah]: "ZEP",
    [BibleBook.Haggai]: "HAG",
    [BibleBook.Zechariah]: "ZEC",
    [BibleBook.Malachi]: "MAL",
    [BibleBook.Matthew]: "MAT",
    [BibleBook.Mark]: "MRK",
    [BibleBook.Luke]: "LUK",
    [BibleBook.John]: "JHN",
    [BibleBook.Acts]: "ACT",
    [BibleBook.Romans]: "ROM",
    [BibleBook.FirstCorinthians]: "1CO",
    [BibleBook.SecondCorinthians]: "2CO",
    [BibleBook.Galatians]: "GAL",
    [BibleBook.Ephesians]: "EPH",
    [BibleBook.Philippians]: "PHP",
    [BibleBook.Colossians]: "COL",
    [BibleBook.FirstThessalonians]: "1TH",
    [BibleBook.SecondThessalonians]: "2TH",
    [BibleBook.FirstTimothy]: "1TI",
    [BibleBook.SecondTimothy]: "2TI",
    [BibleBook.Titus]: "TIT",
    [BibleBook.Philemon]: "PHM",
    [BibleBook.Hebrews]: "HEB",
    [BibleBook.James]: "JAS",
    [BibleBook.FirstPeter]: "1PE",
    [BibleBook.SecondPeter]: "2PE",
    [BibleBook.FirstJohn]: "1JN",
    [BibleBook.SecondJohn]: "2JN",
    [BibleBook.ThirdJohn]: "3JN",
    [BibleBook.Jude]: "JUD",
    [BibleBook.Revelation]: "REV"
}
